nothings/stb

stb_image_write.h

I've added .hdr radiance RGBE support to stb_image_write.h since it could be useful for dumping an hdr screenshot which photoshop or other editors could open, and the encoding isn't too onerous.
I tried to match the code style and follow stb guidelines, I've tested it such as I can (I can't seem to find an image viewer that will open >32768 width files to test that case but inspecting the data loaded by stb_image.h by hand looks fine), and it compiles on what I have available - gcc, clang on linux and VS2010.
If one really wanted to it'd be possible to avoid the malloc() for a scanline but it would make the RLE much more complex I suspect, so I didn't consider it worthwhile.

Add .hdr file writing support

---

stb_image.h

Using stb_image.h. Compiling with Visual Studio 2013, with /W4 and getting:
`stb\stb_image.h(1771) : warning C4244: '=' : conversion from 'int' to 'short', possible loss of data`
`s` is a 4 bit value, so just added a cast.
(My editor trimmed some trailing whitespace)

Fix for warning 4244. Cast to short

---

stb_image.h

The first commit fixes 2 dangling else warnings at lines 1729 and 1765. This way fixes issue #65.
I tired to make the change as small as possible.
Second commit fixes warning unused variable, cause by variable "ha" at line 2424. It looks like a copy paste left over so I simply removed it.

stb image: Fix dangling else and unused variable warnings

---

stb.h

3b1480f is potentially serious as stb_fullpath() reads the first character of its first argument, which at this point contains random stack data.
The rest are mainly silencing warnings.

Various minor fixes that get rid of warnings when compiling on linux

---

stb.h

Hi,
I ran into the errors below when compiling stb.h with VS2013. Most of them are complaints that you can't implicitly cast unsigned short to and from wchar_t because the latter is now a built-in type. It's possible to get rid of them with the `/Zc:wchar_t-` switch, but that's not the default, so I thought it might be good to add some explicit casts.
A couple of the others were about the use of implicit-int or an implicit void return type which are also fixed in this commit.
The only one remaining is the use of `strdup()` instead of `_strdup()`. I didn't want to change that because I don't know if the version with the underscore is available on VC6. In any case that error can be turned off by defining `_CRT_NONSTDC_NO_WARNINGS`.
Thomas
P.S. Thanks for the great library!
```
stb.h(713): …
```

Add explicit wchar_t casts in stb.h

---

tests/caveview/cave_main.c

On an AMD GPU (HD 7800), I experienced severe z-fighting before making this change.

Request a 24-bit depth buffer

---

stb_voxel_render.h

I've added the missing ints required to make code compile as C++ with GCC/G++.
I've also changed a few char* to const char* to make GCC quit complaining about
"deprecated conversion from string constant to 'char*'"

Make code compile as C++ with GCC.

---

stb_image.h

Hi Sean,
We're trying to use stb_image as a drop-in replacement for libjpeg/libjpeg-turbo for IDCT in a project. It's working pretty great - thanks for making this awesome library available! We were scratching our heads for a while why the NEON version wasn't being compiled in on iOS - turns out the SSE2 compiler feature detection is active on non-x86 architectures as well, and STBI_NO_SIMD ends up being #defined even with a #define  STBI_NEON before the #include. Looks like a simple oversight/regression, and the attached patch makes sure the SSE2 detection only is used on x86 architectures. (Not sure x86-64 is worth including there - as far as I'm aware SSE2 is part of the baseline there, but I've left it in just in case)
Thanks
Phil

Fixed bug where NEON code was #ifdef’d out on GCC/clang even with STBI_NEON

---

stb_image.h

This fixes two things. First, the logic to disable SSE2 on
GCC unless "-msse2" was not specific enough, and ended up
disabling SIMD support on NEON targets entirely. Shuffle
the detection logic around to make that bit x86-specific.
Second, 32-bit MinGW assumes 16-byte aligned stacks, but this is
not in the Windows ABI and hence DLLs and callbacks don't
necessarily provide it. This can cause crashes (issue #81).
This can be fixed by providing the right command-line option,
which we have no control over. As a compromise, disable the SSE2
path on MinGW unless a specific #define explained in the comments
is set. That way, we default to safe (never-crashing) behavior
unless the user explicitly signals they know what they're doing.

stb_image: NEON and SSE2 SIMD detection fixes.

---

stb_image.h

GCC 4.7 gave the warning "signed and unsigned type in conditional
expression" because the ternary operator mixes signed and unsigned
integers. Fixed by casting to unsigned inside the "if" branch instead
of casting the result of the entire conditional.

Avoid GCC sign-compare warning.

---

stb_truetype.h

Followed the structure used by stb_rectpack.
Functions that had neither extern neither static got STBTT_DEF  as well.

stb_truetype: added STBTT_STATIC to make all implementation static

---

stb_truetype.h

All operations involved use floating-point, so no need for double literals 0.5. I changed it to floating-point literal 0.5f.

Change double literals 0.5 to float type

---

stb_truetype.h

Changed two places to use STBTT_memset instead of memset like in rest of code so you can replace memset with your own function and prevent including memory.h header.

Couple of places should be using STBTT_memset instead of memset

---

stb_image_write.h

Remove unused variables in write_hdr_scanline.

---

README.md
stb_tilemap_editor.h

Layername buttons will grow/shrink to fill layer panel width. Grows to a maximum of the draw width of the widest set layer name.
Also fixes #47

stbte: layer name buttons grow with layer panel

---

stb_textedit.h

Similarly how stb_truetype.h allows you to replace any stdlib.h, math.h or memory.h function with custom implementation, allow also to replace memmove in stb_textedit.h.

Allow to replace memmove function with custom implementation

---

stb_rect_pack.h

Similarly how stb_truetype.h allows you to replace any stdlib.h, math.h or memory.h function with custom implementation, allow also to replace qsort in stb_rect_pack.h.

Allow to replace qsort function with custom implementation

---

stb_image.h

The original AC decoding logic handled ZRL (runs of 16 zeros)
incorrectly.
The problem is that the original flow set r=16 and skipped the
final coeff write when s=0. This is not actually correct. The
problem is the intervening "refinement" bits.
With the original logic, even once we decrement r to 0, we keep
reading more refinement bits for subsequent coefficients until
we find the next currently-unsent AC in the current scan. That is,
it works as if it was trying to place 17 new AC values, and only
bails at the last minute from actually setting that 17th value.
This is wrong. Once we've found the 16th previously-unsent AC, we
need to stop reading refinement bits, otherwise we get out of sync
with the bit stream (which expects us to read a huffman code next).
The easiest fix is to just do …

stb_image: Progressive AC decoding - fix ZRL code.

---

stb_image.h
stb_vorbis.c

MinGW redefines `__forceinline`, which caused a warning. This was fixed by not redefining it if MinGW has already defined it. A quick google search tells me not every MinGW version out there defines `__forceinline`, which is why it checks if it is defined.
Tested with MinGW and Visual Studio 2013. 
The emitted warning:
```
C:\stb_vorbis.cpp:558:0: warning: "__forceinline" redefined
#define __forceinline inline
^
In file included from C:/Qt/Tools/mingw491_32/i686-w64-mingw32/include/crtdefs.h:10:0,
from C:/Qt/Tools/mingw491_32/i686-w64-mingw32/include/stdio.h:9,
from C:\stb_vorbis.cpp:58:
C:/Qt/Tools/mingw491_32/i686-w64-mingw32/include/_mingw.h:261:0: note: this is the location of the previous definition
#define __forceinline inline __attribute__((__always_inline__))
```

don't redefine __forceinline with mingw

---

stb_truetype.h

fixed the typo in stbtt_GetFontOffsetForIndex, where the field size should be 4 instead of 14.

stb_truetype: fix wrong result returned by stbtt_GetFontOffsetForIndex

---

stb_image.h

Compiling with clang/gcc and -Wall -Wextra and cleaning up all unused variable warnings in `stbi_is_hdr_from_file` and `stbi_is_hdr_from_callbacks`

Fix unused vars warning 

---

stb_image.h

It was incorrectly setting the wrong field to NULL, causing it to get
freed again later.

Fixed double-free in JPEG allocation

---

stb_image.h

This extends the current PSD loader to add support for 16-bit images, by
quantizing them down to 8-bit upon load.

Added support for 16-bit PSD loading.

---

stb_image.h

This PR fixes some warnings that appear in stb_image.h in VS2015 on /W4.
* Variable-shadowing warnings (C4456)
* Converting 32-bit int directly to 64-bit pointer (C4312)

Fix VS2015 warnings in stb_image.h

---

stb_voxel_render.h

It expects constants. The long way compiles (but I haven't actually called this function yet)

DMC doesn't accept struct initializer syntax

---

stb_easy_font.h

It uses the ceil() function but doesn't include math.h itself.

Fix easy_font assuming math.h is already imported

---

stb.h

I'm really unsure on the correctness of the pointer set (stb_ps*) in this state, but it does compile at least.  And stb_sdict works fine, compiled on VS2013 for 64-bit.

Fix 64-bit compilation issues in stb.h

---

stb.h

these are all 64-bit fixes (tested on msvc 2013 community edition).
- __asm keyword not supported on this architecture
- DWORD: missing type specifier - int assumed (*)
- static assert failed, 0-sized element (**)
(*): I assumed that if `_BitScanReverse()` does not complain about `unsigned int n` argument, then `i` should match it as well (just because the output type should match the input one for this function). Or you could just include winbase or windows to fix the missing DWORD declaration (ugh).
(**): I think is ok to have space equal or larger than 16-bytes in this specific case.

msvc 64-bit fixes

---

stb.h

Check for __LP64__ preprocessor define for 64bit. Allocator fix for 64bit.

OSX 64bit fixes

---

stb.h

Fix a few warnings that appear when building a C file including stb.h with the default clang warnings.
Note that the first parameter to `stb_out_backpatch` being an `unsigned int` seems to be a bug as it can be used as the destination for a `memcpy`.
In theory `uintptr_t` would be in theory more appropriate that `size_t` but stb.h does not use `uintptr_t` anywhere and anyway `size_t` will be fine on any platform you care about.

fix clang warnings

---

stb_image_write.h

- Fix a compilation error with gcc -O3.
- Allow to compile the function as static, like stb_image.h does.

Two minor improvements of stb_image_write.h

---

stb_truetype.h

Fix -Wextra warning "-Wmissing-field-initializers" in stb_truetype.h

Fix -Wextra warning in stb_truetype.h

---

stb_image_write.h

Not a lot of extra code for a reasonable size savings. (Cuts the size of my font atlases by about 50-75%.)

stb_image_write: write TGAs with RLE compression

---

tests/oversample/stb_wingraph.h

Very minor but since that file uses the pragma lib facility, gdi32.lib and user32.lib are also required to link. (Tested with tests/oversample/main.c on VS 2010)
for reference
```
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.30319.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.
main.c
Microsoft (R) Incremental Linker Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.
/out:main.exe
main.obj
main.obj : error LNK2019: unresolved external symbol __imp__MessageBoxA@16 referenced in function _stbwingraph_MessageBox
main.obj : error LNK2019: unresolved external symbol __imp__ChangeDisplaySettingsA@8 referenced in function _stbwingraph_ChangeResolution
main.obj : error LNK2019: unresolved external symbol …
```

stb_wingraph.h: missing lib pragmas for completeness

---

stb_image.h

I pulled master and a couple more things showed up...sorry :)
* conversion from int to stbi_uc
* unused parameter

Fix new VS2015 warnings in stb_image 2.07

---

stb_voxel_render.h

Interesting factoid: my last name has four valid spellings. In Germany, the one I use is apparently the most common, while the other spellings are typical in the United States.

fix spelling of "Hofmann"

---

stb_image_write.h

Fix compilation on a project which compiles with warnings as errors and already defines one of these macros.
Also, my editor trims line endings. (lines 101 and 106)

Avoid macro redefinition in Win32

---

stb_image_write.h

When you have Smaller type check /RTCc enabled in MSVS some of the casts can fire off a runtime failure. The bitmask makes sure it is representable as a unsigned char.

Add bitmask to unsigned char casts to fix MSVC runtime checks

---

stb_image_write.h

When compiling with more restrictive compiler options
such casting from double to float will cause a warning.
Ex. GCC -Wdouble-promotion
Signed-off-by: Filip Wasil <filip.wasil@gmail.com>
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/nothings/stb/194)

Removie implicit cast to float

---

stb_image.h

These minor changes avoid defining two unneeded variables (which in turn avoids a compiler warning), and fix an incorrect comment in stb_image.h.

stb_image.h: Don't define unneeded variables, fix an incorrect comment.

---

stb_image.h

If you call any of the `stbi_info*` family of functions right now on a TGA file it can easily break. `stbi__hdr_info` tries to read a token to verify the header, which reads to the next newline or EOF. Even if it then rewinds on failure, the original file header may well be long gone from `s->img_buffer`.
Since there's a nice test function that will only look at the first few bytes it's interested in, using that should be safer.

Fix for stbi_info on TGA files

---

stb_image.h
stb_image_write.h

I often find myself in situations where allocators don't have a realloc feature and querying the size of an allocated block is not possible either. As a workaround I added the previously allocated size as an argument to the STBxx_REALLOC() macros.
Unfortunately, this change breaks backward compatibility for those who redefined the macros. But then, the fix is trivial.

Added the old size as argument to STBI_REALLOC and STBIW_REALLOC

---

stb.h

Simple tweak to enable compiling stb.h with MinGW.
Background: `#ifdef _WIN32` is used to check if compiling with MSVC, but gcc under Windows is also _WIN32 (I guess clang is so too).
The MSVC-specific `intrin.h` is then included for, as far as I can tell, the optimized `_BitScanReverse` in `stb_log2_floor()`. However, 65ebe75124a69193748021fa96eaa6cf660db9b9, already chooses the unoptimized version of `stb_log2_floor()` when compiling with MinGW.
If this is the only use of `intrin.h`, this pull should not break anything.

stb.h: compile fix for MinGW

---

stb.h

deleten was moving memory beyond the array bounds.
insert meant to pass 1 to insertn
insertn was resizing to +i in length instead of +n

Fix stb_arr_insertn and stb_arr_deleten memmove lengths

---

stb.h
stb_tilemap_editor.h

Warning C4703 treated as error with /sdl compiler switch. Also add conditions to prevent _CRT... stuff redefinition.

Warnings C4703 and C4005 fix

---

docs/other_libs.md

EasyEXIF is a tiny, lightweight C++ library that parses basic information out of JPEG files. It uses only the std::string library and is otherwise pure C++. You pass it the binary contents of a JPEG file, and it parses out a few of the most important EXIF fields for you.

Add easy_exif to other_libs.md

---

docs/other_libs.md

[This](https://chiselapp.com/user/dbohdan/repository/picol/home) version is still two files rather than one but in it the REPL has been separated from the library and two embedding examples have been added.

other_libs.md: Add Picol

---

docs/other_libs.md

1. the new fastlz link is a based on a url redirect
- the par_shapes link with `/` is a 4040

Update links for par_shapes, fastlz

---

docs/stb_howto.txt
docs/why_public_domain.md
stb.h
stb_c_lexer.h
stb_divide.h
stb_dxt.h
stb_easy_font.h
stb_herringbone_wang_tile.h
stb_image.h
stb_image_resize.h
stb_image_write.h
stb_leakcheck.h
stb_perlin.h
stb_rect_pack.h
stb_textedit.h
stb_tilemap_editor.h
stb_truetype.h
stb_vorbis.c
stb_voxel_render.h
stretchy_buffer.h

Slightly modify the public domain license to keep it in the public domain, but make it clear that even when dedications might not be recognized that the code is still usable.  Given that this isn't dual-licensing under a different license, I'm hoping this will be acceptable, and considered within the spirit of stb.  This is a wonderful library, and this change makes it more generally usable.

Slightly modify the public domain license

---

stb_voxel_render.h

Should be mat4 or mat4x4, not mat44

typo in shader

---

docs/other_libs.md
stb_image_resize.h
stb_truetype.h
tests/resample_test.cpp

Includes some more tests which had incorrect results before, but work fine with the included fixes. The test does a subpixel region that slides from [0, 0.5] to [0.5, 1] for both upsampling and downsampling. I think that should cover all of the uses of the subpixel stuff. I'm not bothering with s < 0 or t > 1 because I don't think we ever intended to support that in the first place. At the very least, non-subpixel stuff is unaffected because s0 = t0 = 0 means in_shift = 0.

Fix the calculation of the input image shift when using subpixel regions

---

stb_textedit.h

This stem from a user bug report here https://github.com/ocornut/imgui/issues/429
Basically the code expect stb_textedit_click() to typically be followed by stb_textedit_drag(). If other actions are performed in-between the results are usually odd.
Below a reading of what is happening in both cases. This is probably hard to digest and annoying to read, probably easier to test with/without the patch. With the patch seems to match Windows behavior if the users make sure to only call stb_textedit_drag() when mouse is moving and not when mouse is still. If the user keeps calling _drag() every tick behaviour will be different to the user but still more reasonable with patch. At this point Windows does haven't a threshold lock so a single unit of mouse movement triggers the refresh of drag. …

stb_textedit: better support for keying while holding mouse drag button

---

stb_truetype.h

Add a macro to allow fabs() to be provided by the user, as with the other
maths functions. Update the implementation code to use it instead of fasb().
Signed-off-by: Simon Glass <sjg@chromium.org>

ttf: Correct direct use of fabs()

---

stb_image.h

Initial 16 bit per channel PNG support. No float interface yet. This one cleans up a few little things I noticed and fixes a couple of mistakes I missed in the last pull request. Third time's a charm?

Initial 16 bit per channel PNG support

---

stb_vorbis.c

- Removed a unused function. I suspect this might be a real bug:  https://github.com/nothings/stb/blob/master/stb_vorbis.c#L2176 does the same thing in both #if and #else cases, which definitely seems like a typo, but I'm not positive. Hopefully the reviewer will know better.
- Fixed several implicit conversions from 'long' to 'int' and 'unsigned int', most likely surfaced because of my 64-bit target architecture.

Fix a few warnings when building std_vorbis using Xcode 7.2.1

---

stb_image.h
stb_image_write.h

This is so we can compile in our environment, which limits stack frames to < 16Kb.

Allocate large structures on the heap, not stack

---

stb_vorbis.c

Fixes #260:
temp_alloc() and temp_free() are documented as customization points in section "MEMORY ALLOCATION" (stb_vorbis.c:81).
However, in decode_residue() and inverse_mdct() (via temp_block_array() and temp_alloc() respectively), stb_vorbis allocates temporary memory but does not call temp_free() when finished. It does call temp_alloc_restore() though, but there is no sane way to provide an implementation thereof when using a malloc()/free()-like allocation backend.
Adding calls to temp_free() before the respective calls to temp_alloc_restore() is safe, because in case of a non-empty temp_alloc_restore() implementation, temp_free() would simply be implemented empty (the current implementation of temp_*() is fine in this regard). That way, all possible temporary memory allocation …

Fix memory leak in decode_residue() and inverse_mdct() when redefining temp_alloc() and temp_free()

---

stb_vorbis.c

stb_vorbis: Fix memory leak in start_decoder().

---

stb_textedit.h

*EDIT* Minor edits applied since first posting.
Sorry to submit that right after you've done a bunch yesterday!
This patch allows the user to optionally define two functions to override ctrl-arrow style per-word movement, `STB_TEXTEDIT_MOVEWORDLEFT(obj,i)` and `STB_TEXTEDIT_MOVEWORDRIGHT(obj,i)`
`STB_TEXTEDIT_IS_SPACE(ch)` is still supported and will generate default handlers for those, matching the existing code.
The reasoning is to allow applications to:
- Support OS X style word-jumping (move-to-next-word moves to the end of the current word instead of moving you to the beginning of the next word) to have an app be more friendly to OS. Someone made various mods to ImGui to match OS X behaviour and that was the only change they wanted that had to be done on textedit-side.
- Perform …

stb_textedit: Add support for custom move word left/right handlers

---

stb_textedit.h

fix cursor position in the "shouldn't happen, but if it does, fall through to end-of-line case" case (`i=0` causes problems with the return values in this case). 
in my case this happened because STB_TEXTEDIT_LAYOUTROW reported 296.5 pixels, but the individual character sum only made it to 295.5 pixels. the result was the cursor in the middle of the textfield when i was clicking the last pixel of the last character in the last line.

stb_textedit/stb_text_locate_coord:

---

docs/other_libs.md

It provides typesafe dynamic arrays for plain C, but in contrast to stretchy_buffers.h/stb_arr it uses a struct that contains the pointer + count/capacity, which makes it easier to pass the arrays around and modify them elsewhere, with the drawback of having to type `arr.p[i]` instead of `arr[i]` to access elements (otherwise it's pretty similar to stb_arr)

Add DG_dynarr.h to other_libs.md

---

docs/other_libs.md

`ccVector.h` is a single file, C/C++ linear algebra library aimed at graphics development. It provides vectors, quaternions and matrices with utility functions.
All naming schemes are flexible and can be changed to the users preference in the top of the header.
If a vector or matrix with a dimension above 4 or 4x4 needs to be used, a new type and its functions can be created by the macro `CCV_DEFINE_VEC(x)` or `CCV_DEFINE_MAT(x)`.

Add ccVector.h to other_libs.md

---

docs/other_libs.md

The repository has been been relocated by syoyo from [tinyobjloader_c][oldlink] to [tinyobjloader-c][newlink] (note the dash).
[oldlink]:https://github.com/syoyo/tinyobjloader_c
[newlink]:https://github.com/syoyo/tinyobjloader-c

Fix link to tinyobjloader-c

---

README.md
tools/make_readme.c

As the title suggests, this replaces the (truncated) plain filenames with links pointing directly to the relevant files. I probably don't need to tell you that you can see the rendered result on [my fork](https://github.com/1ace/stb/tree/feature/add-link#readme) :)
Note: the generated file was missing `README.header.md`'s contents, but that seems unrelated to my code change, so I just didn't check that bit of the change in. I had a quick look at the code, and couldn't find anything wrong. Probably not worth raising an issue either, esp. considering the importance of that piece of code compared to the rest of the repo :)

README.md: add direct links to files

---

stb_image_resize.h

For example when used on source image of 24000x24000, calculation of in_buffer_row_offset was wrong. Switched to size_t instead.
Test program that was crashing before:
```
#define STB_IMAGE_RESIZE_IMPLEMENTATION
#include "stb_image_resize.h"
#include <memory.h>
int main()
{
size_t kW = 24000;
size_t kH = 24000;
size_t kOutW = 500;
size_t kOutH = 500;
unsigned char* input = (unsigned char*)malloc(kW*kH*4);
unsigned char* output = (unsigned char*)malloc(kOutW*kOutH*4);
stbir_resize_uint8(input, kW, kH, 0, output, kOutW, kOutH, 0, 4);
free(input);
free(output);
return 0;
}
```

stb_image_resize: Fix crash when resizing large images (signed integer overflow)

---

stb_truetype.h

This adds partial implementation of the CFF and Type 2 Charstring specifications. It allows stb_truetype to read most OTF files (or, to be precise, all files I've found to test at the moment).
A few notes:
- This primarily replaces the implementations of `stbtt_GetGlyphBox` and `stbtt_GetGlyphShape` to use the CFF data, but lets the existing TTF code handle everything else. This seems to be pretty sensible - CFF2 explicitly removes almost all the data I'm currently ignoring.
- This adds fields to the `stbtt_vertex` structure, which may be backwards incompatible (as this struct can be replace by the including project).
- It implements all operators from the charstring specification, except for some that were removed in CFF2, and I haven't seen used anywhere.
- Performance is worse - …

CFF and Type 2 charstream parsing in stb_truetype

---

stb_truetype.h

This adds a check for the tag 'true' in stbtt__isfont to support Apple TrueType fonts.
I found this reference at www.microsoft.com/typography/otspec/otff.htm:
NOTE: The Apple specification for TrueType fonts allows for 'true' and 'typ1' for sfnt version.
I've attached an Apple font containing the 'true' tag for testing: [Apple Chancery.ttf.zip](https://github.com/nothings/stb/files/629907/Apple.Chancery.ttf.zip)

Apple TrueType fonts

---

stb_truetype.h

The CFF/Type 2 changes broke including without STB_TRUETYPE_IMPLEMENTATION defined, and had a typo. Sorry!

stb_truetype: Fix a couple of CFF bugs

---

stb_image_write.h

stbi_write_hdr_to_func() should still be available without STBI_WRITE_NO_STDIO,
just like other formats.

Fix "#ifndef STBI_WRITE_NO_STDIO" scope for stbi_write_hdr()

---

stb_sprintf.h

It was matching everything less than 0x26, so could cause a minor performance loss. Also made the second if statement superfluous.

Fix the check for a percent character

---

stb_image_write.h

Now writing out monochrome bitmaps from 8-bit arrays works as it does when using PNG. Bitmaps need 3 bytes per pixel.
I noticed that this was not working when switching from write_png to write_bmp with the same uint8_t-buffer.
Feel free to integrate.

image-write: fix monochrome bitmap writing from 8-bit-buffers

---

stb_vorbis.c

For negative n, the original code went down the "n < (1<<4)"
path and performed an out-of-bounds array access. Fix the code
to agree with section 9.2.1 of the Vorbis spec. (Verified by
exhaustive testing of all 32-bit ints.)
Fixes issue #355.

stb_vorbis: Fix handling of negative numbers in ilog.

---

stb_vorbis.c

Overwrites error parameter in stb_vorbis_open_memory when there is no error. This avoid confusion due to previous values.

Error control in stb_vorbis_open_memory.

---

stb_vorbis.c

`Point` clashes with the struct of the same name in MacTypes.h (included by CoreFoundation.h on macOS/iOS), which breaks stb_vorbis.c when a precompiled header includes these files. (Admittedly, this is only an issue because of my oddball project setup...)
The stb_image libraries use the `stbi__` prefix for internal structs/functions, so I've prefixed this struct with `stbv__`.
I'm not sure that "point" is a descriptive name to begin with. The struct is only used in one place, and the comment states that it's not really a point, but repurposed as something else. Is there a better name for what it is? An "X with index"? Should I rather rename the struct instead of prefixing it?

stb_vorbis: Rename Point to stbv__point

---

stb_image.h

more of "allocate large structures on the stack", this time in the forgotten stbi__jpeg_test
-> avoids the infamous _chkstk() when working without CRT in VisualC++

stb_image.h: large structures on the stack

---

stb_image.h

When reading an RGB JPEG and producing grayscale output, compute Y from RGB instead of outputting R.

stb_image: JPEG: Convert RGB to grayscale properly

---

stb_image.h

Accept JPEG files with any component IDs.
This fix is needed by 6995 images in the ImageNet dataset:
* 6176 have component IDs X, 2, 3 for various values of X (40 values in total, all multiples of 4)
* 714 have component IDs 'Y', 'U', 'V'
* 105 are grayscale with various component IDs (15 values in total, mostly but not all multiples of 4)
At this point it seems best to accept any component IDs rather than trying to code rules for all variants seen in the wild.

stb_image: JPEG: Accept any component IDs

---

stb_image.h

Accept JPEG files with fill bytes (extra 0xff bytes) before markers while huffman decoding.  Fill bytes are currently accepted in stbi__get_marker but not stbi__grow_buffer_unsafe.
This fix is needed by 138 images in the ImageNet dataset.

stb_image: JPEG: Accept fill bytes in stbi__grow_buffer_unsafe

---

stb_image.h

Accept junk bytes having any value (instead of only 0x00) before the marker at the end of image data.
This fix is needed by 2 images in the ImageNet dataset.  Both have a junk byte of 0x7f.

stb_image: JPEG: Accept non-zero junk bytes at the end of image data

---

stb_image.h

Accept JPEG files containing a DNL segment.
This fix is needed by 1 image in the ImageNet dataset.
Note that the image height still must be specified in the frame header, and cannot be delayed until the DNL segment.  This fix just accepts the DNL segment and checks that the height matches the frame header.

stb_image: JPEG: Accept DNL segment

---

stb_image.h

Provide a failure reason when an unknown marker is encountered in a JPEG file.
This is the only case of a missing failure reason that I encountered in the ImageNet data set, though others exist in the code (e.g. "return L==0;" in the same function).

stb_image: JPEG: Provide failure reason for unknown marker

---

stb_dxt.h

As I wanted to compress some tangent space normal maps, I read some articles about the topic and found out that the 3Dc format is very good, and it is actually two DXT5 alpha blocks added together.
The commit shows how easy it would be to support 3Dc here. And that's really about it, since I wasn't sure what to do with the unused 'mode' variable as well as the padding bytes that 'src' requires (they didn't matter for me but they might for someone else).
Any chance you're interested in supporting 3Dc compression explicitly in this library?

stb_dxt: 3Dc support

---

stb_c_lexer.h

```
[stb_c_lexer.h:801]: (error) Memory leak: text
[stb_c_lexer.h:801]: (error) Resource leak: f
```
Found by https://github.com/bryongloden/cppcheck

stb_c_lexer self-test doesn't clean up if file is not found

---

stb_truetype.h

Re: today's DMs -- I found a few cases in stb_truetype where function parameters could safely be const'd. There could very well be others, but these are the ones I hit during my integration. Thanks!

stb_truetype: chardata can be const in GetBakedQuad() and GetPackedQuad()

---

stb_rect_pack.h

This is an extremely minor change.  stbrp_pack_rects returns a result to indicate whether all rects were successfully packed.  It saves having to iterate through the list of rects yourself afterward to determine this.

Return all_rects_packed status from stbrp_pack_rects.

---

stb_sprintf.h

(lower case m is not mega but milli)
More proper fix would probably make these "Kibibytes" etc, as they're 1024 and not 1000 divisors, but this is pretty harmless change.

The Si prefixes for mega, giga and tera are upper case

---

stb_textedit.h

Sean,
Trying to fix an edge case where the Home key (=LINESTART event) wouldn't work if the cursor is the last character of a multi-line buffer and that character isn't a trailing \n.
(
User reports: https://github.com/ocornut/imgui/issues/588
User proposed a fix in `stb_textedit_find_charpos()` but I felt it was too complex and risky: https://github.com/ocornut/imgui/pull/815/files
)
Upon closer inspection today, I stumbled on the fact that the `LINESTART*`, `LINEEND*` events shouldn't really be using `stb_textedit_find_charpos()`. 
It is really overkill: the function calculate a lot of things and is rather confusing already. The fact that it is called from those 4 events increase the confusion and expectation. It is a layout function and effectively does lot of spatial computation that …

stb_textedit.h: fix LINESTART when cursor is at end of buffer + simplifications/optimisations

---

stb_image.h

We're using stbi in https://github.com/uTox/uTox and are working towards `-Werror`, we're willing to disable the indentation warnings, but can't disable these two.
Also, the bit shift was UB, and according to the internet some compilers will and DO optimize out that line.

Fix a pair of warnings in stb_image.h

---

stb_image.h

This fix uses the Adobe APP14 segment and JFIF APP0 segment to detect RGB JPEG files that don't use component IDs 'R', 'G', 'B'.
In the ImageNet dataset, the APP14 check finds 79 additional images but 10 are false positives.  The JFIF check eliminates the false positives.  (Of course I don't know if there are more undetected RGB JPEGs among the 14+ million images in the dataset.)
Some references:
* http://fileformats.archiveteam.org/wiki/JPEG#Color_format
* http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/JPEG.html#Adobe
* https://docs.oracle.com/javase/7/docs/api/javax/imageio/metadata/doc-files/jpeg_metadata.html#color

stb_image: JPEG: Improved detection of RGB images

---

stb_image.h

We tried but it was nothing but trouble. New rule: with GCC/Clang, if you're compiling with -msse2, you get always-on SSE2 code, otherwise you don't get any. Trying to ship anything with proper runtime dispatch requires both working around certain bugs and some fiddling with build settings, which runs contrary to the intent of a one-file library, so bail on it entirely.
Fixes issue #280.
Fixes issue #410.

stb_image: Give up trying to runtime-detect SSE2 on GCC.

---

stb_image.h

My guideline for the rules is the PNG loader (which I consider "canonical"). In the _load functions, x and y are required but comp is optional; in the _info functions, all three are optional.
Fixes issue #411 (and other related, unreported issues).

stb_image: Support optional args consistently.

---

stb_image_resize.h
tests/resample_test.cpp
tests/resample_test_c.c

Apple clang -Wall and -Wextra warnings are all fixed, and all of the MSVC /W4 warnings worth fixing are fixed. Ran the test cases, everything OK.

Fix some STBIR warnings

---

stb_image_write.h

I ported Jon Olick's awesome public domain jo_jpeg.cpp to plain C and to use the stbiw__write_context abstraction instead of plain stdio.
Tested on 64bit Linux with GCC and clang and WinXP with MSVC6.
I noticed that some of the stbi_write_* function definitions were missing STBIWDEF, so I added that.

stb_image_write.h: JPEG writing support based on jo_jpeg.cpp

---

stb_truetype.h

I found a few more function parameters that I believe can be safely const'd, when you have a moment. Thanks!

stb_truetype: fontdata can be const in stbtt_PackFontRange[s]()

---

stb.h
stb_vorbis.c

Add include to `stb.h` and predefine `alloca` function for MINGW

fix: Build on MinGW32

---

stb_image.h

Function `stbi__sse2_available` takes no argument,
we should be explicit by passing `void` as argument.
It will remove warnings from 'some' compilers.

Robustify stbi__sse2_available in stb_image.h

---

stb_image.h

Very small patch to complete the experimental 16 bits interface.

Add stbi_load_16() variants to load from callbacks or memory

---

stb_sprintf.h

This is an attempt to make stb_sprintf at least a bit more readable.
Start with clang-format configured to produce a reasonable semblance of "normal" stb style, then manually fix up a few dodgy pieces of formatting in the result, and finally remove some *really* gratuitous gotos.

Sprintf reformat

---

stb_image.h

We used to require exact match between img_len and raw_len for
non-interlaced PNGs, but the PNG in issue #276 has extra bytes
(all zeros) at the end of the compressed DEFLATE stream.
The PNG spec doesn't have anything to say about it (that I
can tell), and if libpng accepts this, who are we to judge.
Fixes issue #276.

stb_image: Relax raw_len validation for non-interlaced PNGs.

---

stb_image.h

req_comp is now desired_channels and *comp is *channels_in_file.
Fixes issue #466.

stb_image: Documentation fixes.

---

stb_vorbis.c

stb_vorbis: MinGW has alloca defined in malloc.h.

---

stb_image_write.h

* I think it's useful if the compression level can be configured, and it was an easy change, as the builtin compression function already has a "quality" argument.
I just added a global variable (`int stbi_write_png_level`, analogous to `stbi_write_tga_with_rle`) for this. 
* As it has been pointed out in #113, letting stbi_write_png() use an optimized deflate implementation (like from zlib) creates smaller PNGs, closer to libpng. My second commit allows doing that.
I think this is useful, even if it adds an (optional!) dependency, because many projects use zlib, miniz or similar anyway, but might prefer stb_image(_write) over libpng because it's easier to integrate and has a nicer API.

stb_image_write.h: PNG: allow setting zlib compr. level and custom compress function

---

stb_sprintf.h

Haven't tested extensively, but this silences about 800 valgrind errors when starting my game up, with no other issues.

stb_sprintf.h: Don't compare uninitialized value when using zero.

---

stb_image_write.h

Previously, the usage documentation stbi_write_jpg did not include the quality parameter. This PR simply adds it into the usage docs at the top of the file.

Correct function signature in stbi_write_jpg usage documentation.

---

stb_sprintf.h

(GCC recognizes certain strings in comments)

avoid GCC7 implicit-fallthrough warning

---

stb_dxt.h

My clang doesn't like the macro defined this way, choking at the callsite on line 195 with "too many arguments provided to function-like macro invocation"
This change matches what is done for STBTT_memset in stb_truetype.h

Remove argument from STBD_MEMSET macro

---

stb_image.h

It's better to use const qualifier for const tables, data placed to protected .rdata section and duplicates are removed.

place const tables to protected .rdata section

---

stb_image.h

Or else I get this:
```
stb_image.h:896:12: warning: ‘stbi__mad4sizes_valid’ defined but not used [-Wunused-function]
static int stbi__mad4sizes_valid(int a, int b, int c, int d, int add)
^
```

Use stbi__mad4sizes_valid() only if STBI_NO_LINEAR or STBI_NO_HDR are defined

---

stb_truetype.h
tests/test_truetype.c

This is fixes for the stb_truetype header and tests.
- stb_truetype.h - Fix missing function as per bug report #516.
- tests/test_truetype.c: Fix Compiler error on MSVC 2015 or newer.
- tests/test_truetype.c: Fix compiler warning about unsigned/signed conversion.
- tests/test_truetype.c: Fix the png writer.

stb_truetype.h: Fixes

---

stb_image.h

This is similar in spirit to https://github.com/nothings/stb/pull/502
`stbi__float_postprocess` is only used when both `STBI_NO_HDR` and `STBI_NO_LINEAR` are undefined. If I compile stb_image with only `STBI_NO_LINEAR` but without `STBI_NO_HDR`, Xcode (8/9) complains about the now-unused function.

Avoid warning about unused stbi__float_postprocess

---

stb_sprintf.h

avoid warning:
> Variable 'pr' is reassigned a value before the old one has been used
caused by:
fw = pr = fl = 0;
...
pr = 0;

remove duplicated `pr = 0`

---

stb_truetype.h

Coverty scan shows potential warnings of winding_lengths. Forcing it to be a NULL fixes the issue.

stb_truetype: Silence compilation warnings of winding_lengths

---

stb_image_write.h

Fixes #533 for CRT calls that the Microsoft C/C++ compiler considers deprecated and errors when used. The proposed changes are to use the secure versions of these calls if a Microsoft compiler is being used. For this fix, namely, fopen and sprintf.
If you're using an extremely old version of a Microsoft compiler this might be a problem without being more detailed about the _MSC_VER macro.

Using secure CRT calls to avoid MSVC compile errors

---

stb_image_write.h

When computing the PNG filters for the `n`-th row of pixel, the `n-1`-th of the input image was used in all cases (even if the vertical flip flag was true). If the image is to be flipped, the row to use is instead the `n+1`-th row of the initial image. This pull request fixes `stbiw__encode_png_line()` to take this into account.

stb_image_write: Fix error when saving PNG with the stbi__flip_vertically_on_write flag on.

---

stb_rect_pack.h

There's a block of code under `#ifdef _DEBUG` wrap that has those two unused variables.
The full block prior to the patch is copied below. `L1`/`L2` are assigned in the loop but never read.
It's possible that they are frequently useful to have when using a debugger, then instead of merging this patch you could perhaps comment the three lines out?
Copied the patch reported here:
https://github.com/bkaradzic/imgui/commit/1496d97bf62dff1c738ad941c33824ef7c2fc72a#commitcomment-27523479
```
#ifdef _DEBUG
cur = context->active_head;
while (cur->x < context->width) {
STBRP_ASSERT(cur->x < cur->next->x);
cur = cur->next;
}
STBRP_ASSERT(cur->next == NULL);
{
stbrp_node *L1 = NULL, *L2 = NULL;
int count=0;
cur = context->active_head;
while (cur) {
L1 = cur;
cur = cur->next;
++count;
}
cur = …
```

stb_reck_pack: Removed unused assigned variables warnings

---

stb_truetype.h

The functions used by `stbtt_PackFontRanges()` don't skip glyphs that are missing in the font, which result in packing and rasterizing whatever the "fallback" font glyph is. I am using the word "fallback" but I am not sure I really understand if `stbtt_FindGlyphIndex()` returning 0 could _also_ be a valid glyph. 
See #575 about `stbtt_FindGlyphIndex()` documentation.
If I'm taking "Arial Unicode.ttf" and trying to e.g. 32 to 255, notice the squares about 127:
Notice they take space in the font atlas:
(I disabled oversampling here to make this more readable)
While this extraneous space is bearable for a typical ASCII set, when you work with larger sizes, international font ranges, icon font ranges it can be taking more space.
Additionally, this also means that `stbtt_PackFontRanges()` …

stb_truetype: stbtt_PackFontRanges skip missing glyphs.

---

stb.h

Continuing on the changes made in https://github.com/nothings/stb/commit/d85e5946540fca54a3c6bb4d2633817d489e58e7, this replaces the rest of the `unsigned long`s with `unsigned int`s in the stb_rand implementation.

stb.h rand: A few more long->int fixes

---

stb_image_write.h
tests/Makefile
tests/image_write_test.c

Also adding a simple tester app to hopefully reduce this kind of breakage in the future.
(This test works on x64 Linux using clang 7.0.0 with no ASan warnings.)

Fix issue 706

---

stb_rect_pack.h

stbrp__skyline_find_best_pos didn't correctly handle rects too
large to ever fit inside the context. Since that function also
pads the width up to a multiple of the alignment, it makes the
most sense to do that check right after (but before entering
the main packing loop).
While we're here, also fix an off-by-1 bug in the best-fit
heuristic where it didn't want to use the last row in
certain cases.
Fixes issue #701.

stb_rect_pack: Fix two bugs.

---

stb_image.h

1. Check not just g->out allocation for failure; also make sure
that the image allocs don't overflow.
2. If an image descriptor specified a 0-width image, this could be
used to produce an out-of-bounds write.
3. Fix memory leak in case an error occurs during decoding.
Fixes issue #614.
Fixes issue #656.

stb_image: Fix multiple bugs in GIF decoder.

---

stb_image.h

Convince the compiler's dataflow analysis that yes, we are not
reading uninitialized values of coutput.
Fixes issue #608.

stb_image: Pacify some MSVC warnings.

---

stb_image_write.h

this fixes comma warnings when building with -Wcomma
same stuff i pulled for stb_image.h https://github.com/nothings/stb/pull/596 😄 
thanks!

fix comma warnings when building with -Wcomma

---

stb_ds.h

Three commits: take 1, or 1 and 2, or all:
1. Just  use free() instead of realloc(x, 0), no other changes.
2. Use STBDS_REALLOC and STBDS_FREE defines so user can override (globally, ugh).
3. Require STBDS_REALLOC and STBDS_FREE overrides in implementation only (needed stbds_free() wrapper function).

Use free() to free instead of realloc() - Fixes #768, #733

---

stb_truetype.h

As described through twitter, `scale_x` and `scale_y` are both set from `scale`, so it is redundant to check both of them.
Working on this, I noticed some inconsistent white space in stbtt_solve_cubic, using both tabs and spaces. Would you like me to fix this and add it to this pull request?

Remove redundant scale check in stbtt_GetGlyphSDF

---

stb_truetype.h

When calling stbtt_PackFontRanges, multiple missing glyphs in the range of codepoints will cause multiple copies of the font's missing glyph to be added to the pixel buffer.  Instead, the first codepoint that maps to the missing glyph can add it to the pixel buffer, and all subsequent glyphs can simply copy the stbtt_packedchar data to reference the same region of the buffer.
This change does NOT prevent duplication in multiple calls to stbtt_PackFontRange(s) - that would require modifying the packing context, which could be nice but is a bit more intrusive.  I'm open to making the change, but it wasn't necessary for my use case and (I suspect) is a much less significant cause of duplication.
Or, maybe the way I'm using the library is pretty naive, and the missing glyphs are just a …

 stb_truetype: reduce missing glyph duplication

---

stb_ds.h

This is the opposite of urgent or even that important, but just for the sake of my vanity, my name was misspelled here.

typo in credit comment

---

stb_image.h

When building with clang and STB_PNG_ONLY, I got a compile warning about unused functions. This PR fixes this warning. For good measure, I also repeated the same process with all of the following build options:
STBI_ONLY_JPEG
STBI_ONLY_PNG
STBI_ONLY_BMP
STBI_ONLY_PSD
STBI_ONLY_TGA
STBI_ONLY_GIF
STBI_ONLY_HDR
STBI_ONLY_PIC
STBI_ONLY_PNM 
The conventions for #ifdef-ing out a block of code seemed to vary throughout the file, so I did my best to match my #ifdefs with the surrounding ones.

Fix clang unused function compile warnings when compiling with a single decoder

---

LICENSE

The text is copied without modifications from https://github.com/nothings/stb/blob/2f870b3c07e477a5424bc5cc7dc15f90e484ce8f/stb.h#L14415
This makes it a lot easier to find, access and copy LICENSE information.
I'm specifically interested in this as I'm packaging stb for the C/C++ package manager Conan

Create separate LICENSE file

---

stb_vorbis.c

4-byte alignment triggered warnings with clang and -fsanitize=undefined.
Fix #799.
As requested, I looked for a list of contributors to add myself to, but didn't immediately see one. Might be useful to update your pull request template to be explicit where to look.

Pad allocations in setup_{,temp_}malloc for 8-byte alignment

---

stb.h

The stb__splitpath_raw function was incorrectly referring to buffer instead of path while parsing, and was passing the size of the buffer pointer (4 or 8 bytes) rather than the size of the buffer itself, which was causing a crash. Ideally the public interface would take the size of the destination buffer as a parameter also, but in lieu of that, changed to use stb_strncpy because it appeared to already be dealing with this by just assuming target buffer size is n+1.
Also, stb_strncpy had an off-by-1 bug that was truncating the last valid character of the string.

Fix for buffer bugs in stb__splitpath_raw and stb_strncpy

---

stb_vorbis.c

This PR consists of fixes for confirmed bugs in a Coverity Scan of the latest stb_vorbis version.
Commit https://github.com/nothings/stb/pull/854/commits/59e93f58af75aaf10da03e54cad49d623153c128 fixes #839.
Commit https://github.com/nothings/stb/pull/854/commits/0cbb6eeba314652a642cd3eec7400809412d00ca fixes #842.

STB Vorbis: Coverity static-analysis scan fixes

---

stb_voxel_render.h

I copied and pasted the uniform sample code for stb_voxel_render.h, but it was skipping the ambient value because that was mapped to location 0.  I suspect that this was supposed to check if the value was -1, indicating that there was no variable with that name (at least in the version of opengl I am using).

fix possible bug in uniform sample code

---

stb_image_resize.h

VS2019 on /W4 warns about applying '*' to enums. Fixed by casting to int.

Fix VS2019 warning

---

stb_image.h

stb consistently under reads last 4 bytes of *png file. 
in function `stbi__parse_png_file` we have a code:
```c++
static int stbi__parse_png_file(stbi__png *z, int scan, int req_comp)
{
...
for (;;) {
stbi__pngchunk c = stbi__get_chunk_header(s);
switch(c.type) {
...
case STBI__PNG_TYPE('I','E','N','D'): {
...
return 1; // <--- CRC-read, will be skipped because of this 'return'
}
}
...
stbi__get32be(s); // for normal chunk stb reading CRC here
}
}
```
In my video-game I have a screen-shoot inside save-file binary:
```
[ header ][ png-priview ][ data ]
```
And to make it work I need a byte-exact png-reader/writer.

stb_image: fix CRC reading at the end of IEND chunk in png file

---

stb_include.h

Upper bound was incremented each loop instead of iterator causing endless loop when called.

stb_include: fix stb_include_strings iteration

---

stb_image_write.h
stretchy_buffer.h

The `stbi__sbraw()` macro in stb_image_write.h causes Clang to spew about 24 warnings complaining that "cast from '`unsigned char *`' to '`int *`' increases required alignment from 1 to 4" when compiled with the `-Wcast-align` option.
In practice, this is spurious so long as `STBIW_MALLOC()` and` STBIW_REALLOC()` follow the usual alignment semantics for `malloc()` and `realloc()` in that they align sufficiently for any built-in type.
To quell the warning, we can cast through a `void` pointer as an intermediary.

Quell -Wcast-align warnings from Clang

---

stb_sprintf.h

fix: stb_sprintf - gcc defines __powerpc64__

---

stb_vorbis.c

This is a collection of fixes - let me know if you'd like this broken up into separate PRs.
The most important fix is a bad check in `seek_to_sample_coarse` that causes errors when seeking near the end of some pages in many valid files (explained a bit more at https://github.com/nothings/stb/issues/580#issuecomment-536899401 )
The next two fixes are for files with audio data in the header pages. As described in #274 these files violate the spec, but it seems like enough people have had this problem (issues #259,  #580, #597 and #682) to fix it. The fix is different for pushdata, where we can just remove some validation, and pulldata, which already mostly worked, but broke `stb_vorbis_seek_start`.
I also fixed a theoretical bug in my seek code, where seeking near the end of a crazy file …

stb_vorbis seek (and invalid file) fixes

---

stb_image_write.h

fix -Wmissing-variable-declarations clang warning
`stbi__flip_vertically_on_write` is now static like `stbi__vertically_flip_on_load` in `stb_image.h`

stb_image_write: fix clang warning

---

stb_include.h

The current implementation has trouble with the `#inject` feature on *nix systems.  Didn't add name to authors list because it was only one line.

Fix bare backslash n as being a valid whitespace character.

---

stb_leakcheck.h

In some use cases, like low-memory situations on devices without persistent storage, redirecting `stdout` to a file is not an option. But if we want to redirect only the list of leaks, writing it to `stderr` and redirecting only `stderr` to a file is a good solution.

stb_leakcheck: add support for output to stderr

---

stb_image.h

stb_image.h: fix warning about unused function 'stbi__err'

---

stb_image.h

stb_image: fix warning (unused parameter ‘bpc’)

---

stb_easy_font.h

There changes fix posible multiple definition errors when
include stb_easy_font.h header to more then one source file.
Closes #777

stb_easy_font: fix multiple definition errors

---

stb_truetype.h

While it is recommended that the numberOfContours are set to -1 for compound glyphs, it is allowed to have any negative value. Source: https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6glyf.html
However, I don't know if this happens in practice.

Allowing Compound Glyphs with `numberOfContours < -1`

---

stb_image.h

If realloc fails it returns NULL and out pointer becomes invalid. To
fix this it is necessary to store realloc return value in temporary
pointer and then compare it with NULL. If it equals NULL then return
error and source pointer will still valid.
This error was caught by cppcheck:
Common realloc mistake: 'out' nulled but not freed upon failure.

stb_image: fixed 'out' nulled but not freed upon failure

---

stb_truetype.h

The functions are:
stbtt_GetCodepointSVG - provides a pointer to the SVG data in the supplied argument, and returns the length of this data
stbtt_GetGlyphSVG - As above but takes the glyph index instead of the codepoint
These are low-level functions to get access to the data, and make no attempt to decompress it or render a glyph from it!
Fixes #748

Add functions to extract SVG glyphs from font.

---

stb_image.h

stb_image.h:5113:18: warning: comparison of unsigned expression >= 0 is always true [-Wtype-limits]
STBI_ASSERT(v >= 0 && v < 256);
This warning appears when using g++ 8.2 with -Wall -Wextra

Fix gcc warning: expression always true

---

tests/test_sprintf.c

I wanted to have some tests for `stb_sprintf.c` because I was making a few changes to this library. I tried to get good coverage with not too many tests. It's kind of fun watching as the coverage numbers go up. They went up to 99% of lines and 88% of branches.
The tests can be run with either stb_sprintf or glibc sprintf. To run it with glibc change 1 to 0 in the line:
```c
#define USE_STB 1
```
When the output differs I included both version (see `#if USE_STB` in the file). For example, default precision of `%a` differs, capitalization of inf/nan differs, and a couple of other insignificant details.
As for [my changes](https://github.com/project-gemmi/gemmi/blob/master/third_party/stb_sprintf.h) in `stb_sprintf.c` -- I'm not proposing them here because they add dependency on `string.h` …

add tests to tests/test_sprintf.c

---

stb_sprintf.h

avoid this warning:
```
./stb_sprintf.h:1393:51: warning: unused parameter ‘buf’ [-Wunused-parameter]
1393 | static char * stbsp__count_clamp_callback( char * buf, void * user, int len )
|                                            ~~~~~~~^~~
```

stb_sprintf.h: fix unused-parameter warning

---

stb_vorbis.c

Fixes #988.
(The credit update will conflict with #961, but both @RandomShaper and I are happy to rebase our PRs within a few hours once the other is merged.)

stb_vorbis: Add missing error checks in comment reading mallocs

---

stb_image.h

* GCC < 5 supports __thread and GCC >= 5 supports C11 with _Thread_local
* Skip _Thread_local for MSVC because it may not be supported
---
See https://github.com/nothings/stb/issues/967
---
Also I have found these:
1. [Bug 203066 _Thread_local detection is broken with GCC < 4.9](https://lists.freebsd.org/pipermail/freebsd-standards/2015-September/003092.html)
2. [ _Thread_local detection is broken with GCC < 4.9](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203066)
I have updated thread selector like this:
before:
```C
#ifndef STBI_NO_THREAD_LOCALS
#if defined(__cplusplus) &&  __cplusplus >= 201103L
#define STBI_THREAD_LOCAL       thread_local
#elif defined (__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define STBI_THREAD_LOCAL       _Thread_local
#elif defined(__GNUC__)
#define …
```

stbi: fix thread local selector

---

stb_vorbis.c

After updating this file to 1.19 we started having crashes in Godot engine.
It seems there was a change to 64-bit alignment that missed `setup_temp_free()`. This PR fixes the crashes caused by that.
Greetings from Godot!

stb_vorbis.c: Fix missing update to 64-bit alignment

---

stb_image.h

This PR has all the hardening work I did on stb_image:
- Fuzzing inputs with AFL, using a 2x2 image in bmp, gif, jpg, hdr, png, pnm, psd, and tga. (pic not tested). Those files are available in [stbi_afl.zip](https://github.com/nothings/stb/files/4547882/stbi_afl.zip) .
- Running this testsuite through Valgrind and AddressSanitizer: https://code.google.com/archive/p/imagetestsuite/downloads
Testing was done with and without SSE2 support.

stb_image fuzzing fixes

---

stb_vorbis.c

This is needed for `stb_vorbis.c` to compile for the Wii U using devkitPro.
This should theoretically also fix compilation for the Nintendo Switch, 3DS, and Wii (with devkitPro, that is) as they all use Newlib.
Newlib is also used by Cygwin:
https://cygwin.com/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/include/alloca.h;h=5d36318914282280b353aed457e1b1f64947b584;hb=HEAD
And the Google Native Client:
https://chromium.googlesource.com/native_client/nacl-newlib/+/refs/heads/master/newlib/libc/include/alloca.h
As you can see from these links, they both provide `alloca.h` as well, so it appears to be a safe bet that `alloca.h` is available in Newlib.

stb_vorbis.c - Use `__NEWLIB__` for detecting alloca.h

---

stb.h

Fix to buffer issue where stb_strscpy would use + 1 for buffer length when stb_p_strcpy_s is called, causing a stack variable corrupted issue.
Fix to readdir_raw to no longer account for stb_strscpy having + 1 in buffer length.

remove + 1 from stb_strscpy and offset of -1 (n--) in readdir_raw

---

stb_vorbis.c

I propose to remove this line because  f->valid_bits will never be less than zero since, in the while loop, you're adding 8 to it. Therefore, it will always evaluate to false. This is to help remove redundant code!

Added assert(f->valid_bits >= n); on line 1604

---

stb_ds.h

The documentation of that operation already said:
> Returns a pointer to the first uninitialized item added.
This also makes a lot of sense, allowing easy initialization. But the
implementation returned the index of the first uninitialized element
instead.

Fix arraddn returning index instead of pointer

---

stb_dxt.h

A small change to quantize floating point endpoints to RGB565 exactly. This improves quality slightly. For more info see: https://gist.github.com/castano/c92c7626f288f9e99e158520b14a61cf

Perfect quantization of DXT endpoints

---

stb_image.h

This is a pretty straightforward fix. I introduce 2 new integer variables to keep track of the sizes of 2 buffers and replaced the calls to `STBI_REALLOC` with `STBI_REALLOC_SIZED`.
This also fixes issue #765

Refactored stbi__load_gif_main to use STBI_REALLOC_SIZED instead of STBI_REALLOC

---

stb_vorbis.c

Some distributions of MinGW define `alloca` themselves which causes warnings about stb_vorbis' `alloca` macro being a redefinition. This change just wraps it in a `#ifndef / #endif` block.

stb_vorbis: Fix macro redefinition warning on MinGW.

---

stb_ds.h

Fix `temp_key` being stale on key re-insert. This pull request re-uses the existing key, which matches the previous behavior. Before the fix, there was a chance that `temp_key` would be the last inserted key, or effectively garbage data. This manifested for me in double frees and entries with incorrect keys.
See issue nothings#992 and pull request nothings#993.

shputs duplicate insert: fix stale temp_key

---

stb_image.h

Fixes two availability issues in stb_image that could occur with specially
constructed HDR and PGM files. Please see issues #1224 and #1225 for full descriptions.
HDR: In certain conditions, the RLE decoder can get stuck in the decoding loop
at the end of a stream: `stbi__get8()` always returns 0 when at the end of a
stream, which is interpreted as a count and results in an infinite loop.
I believe the solution is to treat a run of 0 as invalid, following the
`RGBE_ReadPixels_RLE()` function in Bruce Walter's
[https://www.graphics.cornell.edu/~bjw/rgbe/rgbe.c](https://www.graphics.cornell.edu/~bjw/rgbe/rgbe.c).
PGM: Loading large monochrome 16-bit PGM files would cause an access violation
due to reading out of bounds when comverting from 16-bit to 8-bit. In addition,
when loading 16-bit …

Fixes a crash and an infinite loop in stb_image that could occur with specially constructed PGM and HDR files

---

stb_image.h

Hi stb maintainers! I went through the first ten ossfuzz issues (up to and including ossfuzz issue 38394) and put together fixes for them. About half were duplicates of previous issues, but three were new and are fixed in this PR.
I also went through the test files in issues #1289, #1291, #1292, and #1293 and fixed ASan+UBSan reports from loading those issues' repro cases which weren't already fixed by #1223 or #1230.
Here are the bugs, some quick analyses, and their fixes:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22620&q=proj%3Dstb&can=2 :
This is a PNM file with specifies a width of 3333333333. Parsing this integer overflows a signed 32-bit integer.
The fix I chose isn't the most elegant: I check to see if value * 10 + (*c - 0) would overflow a signed int, and then …

Additional stb_image fixes for bugs from ossfuzz and issues 1289, 1291, 1292, and 1293

---

stb_image_resize2.h

Charles reported a slight darkening of alpha on one output scanline of a 2052 to 256 resample (instead of a 1.0 expected output, it would be 0.99681 across one scanline).
The summary is that this was a bug in the pivot code (we always build the coefficients in gather mode, and then pivot them for scatter mode). Basically, an extra aligning zero coefficient in the gather mode list could sometimes cause the pivoter to overwrite the next scatter coefficient's list weight. Since this overwrote the smallest coefficient, the effect was subtle, and I missed it in my test thresholds.
The bug was tricky to track down, since:
1) We only use scatter on vertical scaling
2) We only use scatter when the vertical scaling is more than 3x
3) The extra aligning coefficient only gets inserted on the …

Fix bug in coeff gen on more than 3x downsamples with w and h equal

---

stb_image_resize2.h

- fix for slow final split during threaded conversions of very wide scanlines when downsampling (caused by extra input                         converting)
- fix for wide scanline resamples with many splits (int overflow)
- fix GCC warning.

image resize 2.07

---

stb_image_resize2.h

* Delete this list before clicking CREATE PULL REQUEST
* Make sure you're using a special branch just for this pull request. (Sometimes people unknowingly use a default branch, then later update that branch, which updates the pull request with the other changes if it hasn't been merged yet.)
* Do NOT update the version number in the file. (This just causes conflicts.)
* Do add your name to the list of contributors. (Don't worry about the formatting.) I'll try to remember to add it if you don't, but I sometimes forget as it's an extra step.
If you get something above wrong, don't fret it, it's not the end of the world.

resize 2.10 - fix gcc loop control and msvc arm32

---

stb_image_resize2.h

Resize 2.11 fixes a asan crash when using separate mallocs (#1676), fixes point sample crash (#1678).

image resize 2.11 - fix harmless asan, fix point sample crash

---

stb_image_resize2.h

`stb_image_resize2.h:6734:5: runtime error: member access within null pointer of type 'stbir__info' (aka 'struct stbir__info')`
ASAN detects this (where Valgrind didn't).

Fix STBIR__FREE_AND_CLEAR causing null reference member access

---

stb_image_resize2.h

fixed a nan bug using downsampling gather horizontal first, and scatter with vertical first.

resize 2.14 - fix off edge nans leaking in on some resize types

---

tools/README.header.md

Fixed a typo in the header file of README. Changed "lastest" to "latest".
Contributor name : CodeAlpha07 (Devu Gupta)

Fixed typo in readme.header.md
