nothings/stb

- stb_voxel_render.h
Just a couple of typos.
Cheers!
> I like the word 'implementation'

- stb_image.h
strawman number 2, continued from #89.
> added stbi_vertically_flip_on_load

- stb_image.h
This fixes various crashes on malformed input files.
> Fixing various crashes when loading jpg, png and tga images.

- stb_image_write.h
Adding memory and assert defines to stb_image_write to match stb_image
> Adding memory and assert defines to stb_image_write

- stb_voxel_render.h
Fixes #143 
Thanks for your time Sean,
Chris
> Adds up and down checks to voxel render input.geometry

- stb_image.h
I adapted stb_image so it lets me load gif images and animations properly so I figured I could share these changes.
There are two main things I'm changing here:
1. GIF background is made transparent where expected.
2. `stbi__gif_load_next()` was adapted so it can be used to correctly load GIF animations, with (hopefully) proper handling of disposal methods.
There was also a possible memory leak in case of loading failure: `stbi__gif_load_next()` would allocate a buffer but return NULL in some cases, and buffer never gets freed or returned to the user.
I made some test cases comparing the currently official implementation vs this modified version so these changes are more clearly visible. Basically, I loaded a bunch of gif samples and saved them as PNG using stb_image_write. Here are the …
> GIF loading improvements.

- stb.h
> Fix double free() in stb.h

- stb.h
Made minor changes to stb.h to compile cleanly under MinGW. There were 4 issues dealt with:
1) MinGW is _WIN32, but uses GCC assembler semantics, not Microsoft style. Added an additional preprocessor check to only compile the assembly optimized version of stb_log2_floor on Windows platforms that are not MinGW.
2) Calls to _wstat were expecting a _stat struct, not a stat. This is due to Win32 using _stat, but stb was only checking for MSC_VER. Expanded the preprocessor check to include MinGW as well.
3) mkstemp() is not available in MinGW. Added a conditional workaround using mktemp() [less secure, but functional for now] wrapped in open(). This necessitated including fcntl.h for the O_RDWR parameter to open.
4) stb_dirtree_get_dir had an invalid double slash character. Removed the …
> Tweaked to enable compilation under MinGW.

- stb.h
- stb_easy_font.h
- stb_leakcheck.h
- stb_tilemap_editor.h
- stb_vorbis.h
Compiling with Visual Studio 2015 requires a few changes.  Most items contained within #ifdef _WIN32 blocks.
> Updated to compile with Visual Studio 2015

- stb_image_write.h
I tried to respect what was done in stb_image.h as much as possible with a few modifications so that stb_image.h and stb_image_write.h can be used in the same compilation unit.
> stb_image_write.h: Add support for writing through callback functions

- docs/other_libs.md
Lightweight URL & URI parser (RFC 1738, RFC 3986)
> Added LUrlParser

- stb_image.h
16bit TGAs were always loaded as greyscale+alpha, even if the TGA image type was not 3 or 11 (the types for greyscale images). However, when not grey, it's supposed to be RGB555 (potentially with an
1-bit alpha-channel in the MSB).
Those kind of images are supported now, also when using a colormap (palette) with 16bit colors in them. It's converted to `STBI_rgb` or `STBI_rgb_alpha`.
`stbi__tga_info()` didn't correctly calculate the pixelformat (`comp`) for colormapped images - it used the TGA's "normal" bits per pixel field instead of the one for the colormap.
For some reason `stbi__tga_test()` used `stbi__get16be()`, even though TGA is little endian.
Furthermore I improved both functions to do some more sanity checks and to consistently rewind the context.
I tested the code with TGA test …
> stb_image.h: Improve TGA support, incl. 16bit support

- docs/other_libs.md
Parson is a 2-file (.h and .c) JSON parser and serializer written in C.
> Adds parson to other_libs.md

- docs/other_libs.md
Hi. I love your code!
I was wondering if you might consider adding my small C libraries to your `other_libs` list: [TinyExpr](https://github.com/codeplea/tinyexpr) and [minctest](https://github.com/codeplea/minctest).
> Added minctest and tinyexpr.

- docs/other_libs.md
> other_libs.md: Update Picol

- docs/other_libs.md
Header-only Poisson disk generator library
https://github.com/corporateshark/poisson-disk-generator
> Added PoissonGenerator.h

- docs/other_libs.md
I think this library fits perfectly
- It's a single source file
- The license is included in the file itself
- It's a really useful tool
> Add @vurtun his nuklear library to Other Libraries

- docs/other_libs.md
> tigr now supports osx

- docs/other_libs.md
Hi,
I was wondering if you'd add Genann to your other_libs list? It's a neural network library in C - one source file, one header file, callable from C++, zlib license.
Thanks!
> Added Genann (neural networks)

- stb_image.h
Fix several bugs found by fuzzing or plain old inspection.
Fixes #310, #311, #312, #313, #314, #315, #317, #318. (All confirmed fixed
on Linux running GCC-6.1.1 with ASan using provided repro files)
> Fix several bugs.

- stb_truetype.h
This PR adds the function stbtt_GetNumberOfFonts to determine the number of fonts in a .ttc or .ttf file.  It uses the same basic code as asstbtt_GetFontOffsetForIndex, as well as following the structure of encapsulating internal methods from the API (stbtt_GetNumberOfFonts calls stbtt_GetNumberOfFonts_internal).
Note that the code to check for Apple TrueType fonts from PR #375 is NOT included in this PR.
> Number of fonts in a TrueType file

- stb_image.h
stbi_uc was truncating to an 8 bits
> allow for all 16 bits

- stb_image.h
Accept JPEG files with 16-bit quantization tables.
This fix is needed by 625 images in the ImageNet dataset.
> stb_image: JPEG: Accept 16-bit quantization tables

- stb_sprintf.h
The reused code is also easier to read.
> stb_printf.h: Reuse code for assigning lead sign.

- stb_image.h
Static initialization of constants stbi__zdefault_length and stbi__zdefault_distance.
> stb_image: Static initialization of constants

- stb_image.h
> stb_image: Fix STBI_NO_STDIO

- stb_dxt.h
> stb_dxt: 	Add STB_DXT_STATIC option

- stb_dxt.h
This PR leverages the changes introduced for BC5 and adds support for BC4.
> Add support for BC4

- stb_image.h
- stb_image_resize.h
Fix a few compiler warnings I found when using /W4 on VS 2015.
> Fix VS2015 warnings

- stretchy_buffer.h
> Fixing void * compile error for C++

- stb_image_write.h
This adds a new `stbi_write_png_to_mem_ex` function with two new parameters:
* `force_filter` being < 0 means the original behavior (i.e. figure out the best-performing filter per scanline); any other values 0 <= x <= 4 correspond to PNG filters (0 = none, 1 = sub, 2 = up, 3 = average, 4 = Paeth).
* `compression_level` being < 0 equals `compression_level` 8 (the previous value). The higher this is, the better the compression should be (though it will use more memory).
These new parameters are not (yet) exposed for the higher-level API functions, and the documented API does not change as of this commit.
For what it's worth, encoding a 1920x1080 image  with `force_filter=0` is about 45% faster than `force_filter=-1` on my particular machine.
> stb_image_write: allow forcing PNG filter and compression

- stb.h
Someone should double check that that I didn't change
the behavior of any of the code.  I'm not using most (if any)
of the code I touched, just wanted it to compile...
> Fix compile errors on clang++

- stb_image.h
Add some code to load 1-bit BMP's
> stb_image: support for 1-bit BMP

- stb_tilemap_editor.h
- tests/Makefile
I have another PR which already adds me to contributors.
> Fix tests compilation

- stb_image.h
To test for 16 bit images.
I also modified stbi__psd_info to not return 0 in case of 16 bit (to be consistent with stbi__psd_load).
> stbi_is_16

- stb_truetype.h
@nothings  @dougallj I have implemented a very simple 'stbtt_GetGlyphGPOSAdvance' function which retrieves GPOS-based kerning advances. It is far from complete (Horizontal latin stuff mostly), but it works for all the GPOS-based fonts I'm currently using plus a few others.
I have added some asserts which people might hit in case their fonts require a specific unimplemented format. Let me know if you hit one of those.
I have also not implemented any binary searching, so it is a little bit slow. I'm not sure how important it is to implement binary search there, I might experiment with it at some point maybe on this or next week?
Best regards,
Daniel
> Add basic GPOS kerning

- stb_image.h
> stb_image: Fix typo in comment.

- stb_ds.h
Small documentation correction on the stb_ds.h
> Add arrpop function to stb_ds

- stb_ds.h
> stb_ds.h: hmlen and hmlenu now returns 0 on NULL pointer

- stb_image_write.h
For quality <= 90, it now supports subsampling U and V so it encodes smaller files.
https://www.jonolick.com/home/jo_jpeg-release-160 has more information about jo_jpeg 1.60
> stb_image_write: Update JPEG code to jo_jpeg 1.60

- stb_sprintf.h
> C++ commits

- stb_vorbis.c
This PR implements the the reading of ogg comments from the Second packet in the vorbis specification https://xiph.org/vorbis/doc/Vorbis_I_spec.html#x1-820005
The comment reading should be page-agnostic and be able to serve cases where the comment packet spans multiple segments or pages.
I'm not sure which errors to throw when encountering invalid data in this packet.  I have used VORBIS_invalid_setup for these cases but let me know if there's something better.
> Add comment support to stb_vorbis

- stb_perlin.h
* Make sure you're using a special branch just for this pull request. (Sometimes people unknowingly use a default branch, then later update that branch, which updates the pull request with the other changes if it hasn't been merged yet.)
Whoops. Anyways, this is needed for doing custom fractal stuff.
> stb_perlin: extern stb_perlin_noise3_seed

- stb_ds.h
- stb_vorbis.c
Hi there. I fixed some warnings that GCC issues when in pedantic mode. Hope it helps.
> Fixing some pedantic warnings for GCC

- stb_ds.h
This commit fixes the issue of inserting a struct to strdup and arena hastable.
Downside of this change is that it introduces additional instructions (also for default string hashtable)
but inserted code should have negligible overhead because it is easy to predict.
Feel free to reject this change if you think that it does not make sense
or it is not worth additional complexity.
> stb_ds: fix shputs() for strdup and arena hash table

- stb_image.h
Is as it says on the tin. Found a minor typo in one of the comments and fixed it.
> Fix minor typo in comment on line 6532

- tests/stb_c_lexer_fuzzer.cpp
I will get a pull request going on OSS-fuzz for the necessary updates in the build to run this fuzzer.
> Added fuzzer for stb_c_lexer

- stb_dxt.h
Integrate Rich's changes as discussed here:
https://twitter.com/richgel999/status/1246212783445770248
I've confirmed the changes improve quality slightly. I don't have exact numbers at hand right now, but if in doubt I can run my tests again.
> Integrate more accurate index selection by Rich Geldreich.

- stb_image.h
This fixes two issues with an assert failing. I tested that the first part fixes #909 and the second fixes #897.
A.  Loading 16/24/32-bit BMP from memory caused an assert to fail (excluding 16-bit BMP with `hsz` 12).
`img_buffer` offset was always compared with the buffer for `stbi_load_from_file()` but `stbi_load_from_memory()` uses an external buffer.
Resolution: Change `s->buffer_start` to `s->img_buffer_original`.
B. Loading BMP with large header from file caused assert to fail.
`img_buffer` points to `stbi_uc buffer_start[128]` but the largest BMP supported has a 138 byte header (`hsz` 124) causing `img_buffer` to wrap around to an offset of 10. The assert fails because 138 (header size) != 10 (offset in temp read buffer).
Resolution: Add the previously read bytes to the offset in …
> stb_image: fix assert failing when loading BMP

- stb_ds.h
> stb_ds.h: fix unused parameter warning

- stb_ds.h
Fixes issue described in #1141
> Fix custom realloc/free bug in stb_ds

- tests/ossfuzz.sh
Follow-up from https://github.com/nothings/stb/pull/1058#issuecomment-877736188, by the way changes to the Dockerfile didn't break builds with `master` and everything should keep working after the merge, the solution wasn't that messy: https://github.com/google/oss-fuzz/pull/6023/files#diff-37336c5e77cb828028037c3ed7fa8f099fa00a0d25693f6b3f612e46bd119557R35
> Fix CIFuzz integration

- stb_ds.h
Fixes #1011.
As intended according to https://github.com/nothings/stb/pull/932#issuecomment-657524197.
> Rename arraddnoff -> arraddnindex

- stb_image_resize2.h
2.09 resize - fix defines for GCC arm 32
> 2.09 resize - fix defines for GCC arm 32

- stb_image_resize2.h
fixed a bug when using input callbacks, 
turned off simd for tiny-c, 
fixed some variables that should have been static, fixes a bug when calculating temp memory with resizes that exceed 2GB of temp memory (very large resizes).
> Resize 2.13 -
